### ISSUE TITLE
Building wheel fails when installing with pip

### ISSUE THREAD

**Issue by patrickayoup** [patrickayoup/backup_now#2]
$ pip install backup_now --user
Collecting backup_now
  Downloading backup_now-1.0.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): fasteners in ./.local/lib/python3.5/site-packages (from backup_now)
Requirement already satisfied (use --upgrade to upgrade): monotonic>=0.1 in ./.local/lib/python3.5/site-packages (from fasteners->backup_now)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3.5/site-packages (from fasteners->backup_now)
Building wheels for collected packages: backup-now
  Running setup.py bdist_wheel for backup-now ... error
  Complete output from command /bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_hnggf86/backup-now/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpc1j9ttrkpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/backup_now
  copying backup_now/__init__.py -> build/lib/backup_now
  copying backup_now/__main__.py -> build/lib/backup_now
  creating build/lib/backup_now/resources
  copying backup_now/resources/__init__.py -> build/lib/backup_now/resources
  running build_scripts
  creating build/scripts-3.5
  copying bin/backup_now -> build/scripts-3.5
  changing mode of build/scripts-3.5/backup_now from 664 to 775
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/backup_now
  creating build/bdist.linux-x86_64/wheel/backup_now/resources
  copying build/lib/backup_now/resources/__init__.py -> build/bdist.linux-x86_64/wheel/backup_now/resources
  copying build/lib/backup_now/__main__.py -> build/bdist.linux-x86_64/wheel/backup_now
  copying build/lib/backup_now/__init__.py -> build/bdist.linux-x86_64/wheel/backup_now
  running install_egg_info
  running egg_info
  writing backup_now.egg-info/PKG-INFO
  writing requirements to backup_now.egg-info/requires.txt
  writing dependency_links to backup_now.egg-info/dependency_links.txt
  writing top-level names to backup_now.egg-info/top_level.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'backup_now.egg-info/SOURCES.txt'
  writing manifest file 'backup_now.egg-info/SOURCES.txt'
  Copying backup_now.egg-info to build/bdist.linux-x86_64/wheel/backup_now-1.0.0-py3.5.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/backup_now-1.0.0.data
  creating build/bdist.linux-x86_64/wheel/backup_now-1.0.0.data/scripts
  copying build/scripts-3.5/backup_now -> build/bdist.linux-x86_64/wheel/backup_now-1.0.0.data/scripts
  changing mode of build/bdist.linux-x86_64/wheel/backup_now-1.0.0.data/scripts/backup_now to 775
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-_hnggf86/backup-now/setup.py", line 95, in <module>
      keywords=['backups', 'duplicity']
    File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/usr/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 364, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.linux-x86_64/wheel/backup_now-1.0.0-py3.5.egg-info but not found
  
  ----------------------------------------
  Failed building wheel for backup-now
  Running setup.py clean for backup-now
Failed to build backup-now
Installing collected packages: backup-now
  Running setup.py install for backup-now ... done
Successfully installed backup-now-1.0.0

**Comment by patrickayoup** [comment]
Follow Procedure: http://pythonwheels.com/
